# Generated by Django 4.0.2 on 2022-02-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermodel',
            name='temprature',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
